### PR TITLE
Merging to version 0.8.0

### PR DESCRIPTION
**Pull request by awbarclay**
I recently updated a some baseline evaluation functions, and I would like to merge the feature branch to develop before merging to the main branch. I added an option to use .fst files for most of the functions, but I also made some improvements and fixed bugs in a few functions. The biggest changes were made to `summarize_rubias_baseline_eval()` and `custom_combine_rubias_output()`. 

@krshedd, @csjalbert, @tylerdann, and @emlee-ak, would you please review these functions and make sure I didn't break anything? I'm mainly worried about `custom_combine_rubias()` because it's used by project leaders on a regular basis for MSAs and there are a number of ways it can summarize rubias output.  Maybe you could re-summarize some old output to makes sure it still works? It would also be nice if you could test `summarize_rubias_baseline_eval()` with some old eval results if you have them.  I'd like to have this merged by the end of the week if possible. Thank you for your help!

### CODE REVIEW

**Review by krshedd — APPROVED** [review]
Awesome job @awbarclay, these are great improvements. I made a few small changes to make sure the examples work for `summarize_rubias_base_eval` and `custom_comb_rubias_output` as well as some cosmetic changes to the documentation. I tested `custom_comb_rubias_output` on some old output in various ways (w/ and w/o bias correction, rolling up fine-scale groups to broad-scale groups, w/ and w/o multichain, etc.) and did not have any issues. All looks okay to merge!

**Comment by awbarclay** [comment]
@krshedd, thanks for the edits and testing! @csjalbert, @tylerdann, and @emlee-ak, unless you really want a chance to review my updates and test, I think I'm going to merge today so main is up to date.

**Comment by tylerdann** [comment]
I'm comfortable with Kyle testing and if you are comfortable merging.
Thanks!

**Comment by awbarclay** [comment]
I'm going to assume that @csjalbert doesn't need to review and merge soon.

**Comment by csjalbert** [comment]
@awbarclay I am good to merge. Thanks.

**Pull request merged**
